// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oryvwqfbeuyiuomnnlhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeXZ3cWZiZXV5aXVvbW5ubGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDE5MTIsImV4cCI6MjA1NDc3NzkxMn0.jS0uHXKhMF3ZQJ8QpcrWdFBxeriswLm5DGf5yzCt9HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});